version: '3'
services:
  api:
    container_name: api-container
    image: api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"